/* eslint-disable import/prefer-default-export */
export const keyCodes = {
  0: {
    code: 'Backquote',
    descriptionEng: '§',
    descriptionEngCups: '±',
    descriptionRu: '&gt;',
    descriptionRuCups: '&lt;',
  },
  1: {
    code: 'Digit1',
    descriptionEng: '1',
    descriptionEngCups: '!',
    descriptionRu: '1',
    descriptionRuCups: '!',
  },
  2: {
    code: 'Digit2',
    descriptionEng: '2',
    descriptionEngCups: '@',
    descriptionRu: '2',
    descriptionRuCups: '"',
  },
  3: {
    code: 'Digit3',
    descriptionEng: '3',
    descriptionEngCups: '#',
    descriptionRu: '3',
    descriptionRuCups: '№',
  },
  4: {
    code: 'Digit4',
    descriptionEng: '4',
    descriptionEngCups: '$',
    descriptionRu: '4',
    descriptionRuCups: '%',
  },
  5: {
    code: 'Digit5',
    descriptionEng: '5',
    descriptionEngCups: '%',
    descriptionRu: '5',
    descriptionRuCups: ':',
  },
  6: {
    code: 'Digit6',
    descriptionEng: '6',
    descriptionEngCups: '^',
    descriptionRu: '6',
    descriptionRuCups: ',',
  },
  7: {
    code: 'Digit7',
    descriptionEng: '7',
    descriptionEngCups: '&amp;',
    descriptionRu: '7',
    descriptionRuCups: '.',
  },
  8: {
    code: 'Digit8',
    descriptionEng: '8',
    descriptionEngCups: '*',
    descriptionRu: '8',
    descriptionRuCups: ';',
  },
  9: {
    code: 'Digit9',
    descriptionEng: '9',
    descriptionEngCups: '(',
    descriptionRu: '9',
    descriptionRuCups: '(',
  },
  10: {
    code: 'Digit0',
    descriptionEng: '0',
    descriptionEngCups: ')',
    descriptionRu: '0',
    descriptionRuCups: ')',
  },
  11: {
    code: 'Minus',
    descriptionEng: '-',
    descriptionEngCups: '_',
    descriptionRu: '-',
    descriptionRuCups: '_',
  },
  12: {
    code: 'Equal',
    descriptionEng: '=',
    descriptionEngCups: '+',
    descriptionRu: '=',
    descriptionRuCups: '+',
  },
  13: {
    code: 'Backspace',
    description: 'delete',
  },
  14: {
    code: 'Tab',
    description: 'tab',
  },
  15: {
    code: 'KeyQ',
    descriptionEng: 'q',
    descriptionEngCups: 'Q',
    descriptionRu: 'й',
    descriptionRuCups: 'Й',
  },
  16: {
    code: 'KeyW',
    descriptionEng: 'w',
    descriptionEngCups: 'W',
    descriptionRu: 'ц',
    descriptionRuCups: 'Ц',
  },
  17: {
    code: 'KeyE',
    descriptionEng: 'e',
    descriptionEngCups: 'E',
    descriptionRu: 'у',
    descriptionRuCups: 'У',
  },
  18: {
    code: 'KeyR',
    descriptionEng: 'r',
    descriptionEngCups: 'R',
    descriptionRu: 'к',
    descriptionRuCups: 'К',
  },
  19: {
    code: 'KeyT',
    descriptionEng: 't',
    descriptionEngCups: 'T',
    descriptionRu: 'е',
    descriptionRuCups: 'Е',
  },
  20: {
    code: 'KeyY',
    descriptionEng: 'y',
    descriptionEngCups: 'Y',
    descriptionRu: 'н',
    descriptionRuCups: 'Н',
  },
  21: {
    code: 'KeyU',
    descriptionEng: 'u',
    descriptionEngCups: 'U',
    descriptionRu: 'г',
    descriptionRuCups: 'Г',
  },
  22: {
    code: 'KeyI',
    descriptionEng: 'i',
    descriptionEngCups: 'I',
    descriptionRu: 'ш',
    descriptionRuCups: 'Ш',
  },
  23: {
    code: 'KeyO',
    descriptionEng: 'o',
    descriptionEngCups: 'O',
    descriptionRu: 'щ',
    descriptionRuCups: 'Щ',
  },
  24: {
    code: 'KeyP',
    descriptionEng: 'p',
    descriptionEngCups: 'P',
    descriptionRu: 'з',
    descriptionRuCups: 'З',
  },
  25: {
    code: 'BracketLeft',
    descriptionEng: '[',
    descriptionEngCups: '{',
    descriptionRu: 'х',
    descriptionRuCups: 'Х',
  },
  26: {
    code: 'BracketRight',
    descriptionEng: ']',
    descriptionEngCups: '}',
    descriptionRu: 'ъ',
    descriptionRuCups: 'Ъ',
  },
  27: {
    code: 'Backslash',
    descriptionEng: '\\',
    descriptionEngCups: '|',
    descriptionRu: 'ё',
    descriptionRuCups: 'Ё',
  },
  28: {
    code: 'CapsLock',
    description: 'caps lock',
  },
  29: {
    code: 'KeyA',
    descriptionEng: 'a',
    descriptionEngCups: 'A',
    descriptionRu: 'ф',
    descriptionRuCups: 'Ф',
  },
  30: {
    code: 'KeyS',
    descriptionEng: 's',
    descriptionEngCups: 'S',
    descriptionRu: 'ы',
    descriptionRuCups: 'Ы',
  },
  31: {
    code: 'KeyD',
    descriptionEng: 'd',
    descriptionEngCups: 'D',
    descriptionRu: 'в',
    descriptionRuCups: 'В',
  },
  32: {
    code: 'KeyF',
    descriptionEng: 'f',
    descriptionEngCups: 'F',
    descriptionRu: 'а',
    descriptionRuCups: 'А',
  },
  33: {
    code: 'KeyG',
    descriptionEng: 'g',
    descriptionEngCups: 'G',
    descriptionRu: 'п',
    descriptionRuCups: 'П',
  },
  34: {
    code: 'KeyH',
    descriptionEng: 'h',
    descriptionEngCups: 'H',
    descriptionRu: 'р',
    descriptionRuCups: 'Р',
  },
  35: {
    code: 'KeyJ',
    descriptionEng: 'j',
    descriptionEngCups: 'J',
    descriptionRu: 'о',
    descriptionRuCups: 'О',
  },
  36: {
    code: 'KeyK',
    descriptionEng: 'k',
    descriptionEngCups: 'K',
    descriptionRu: 'л',
    descriptionRuCups: 'Л',
  },
  37: {
    code: 'KeyL',
    descriptionEng: 'l',
    descriptionEngCups: 'L',
    descriptionRu: 'д',
    descriptionRuCups: 'Д',
  },
  38: {
    code: 'Semicolon',
    descriptionEng: ';',
    descriptionEngCups: ':',
    descriptionRu: 'ж',
    descriptionRuCups: 'Ж',
  },
  39: {
    code: 'Quote',
    descriptionEng: '\'',
    descriptionEngCups: '"',
    descriptionRu: 'э',
    descriptionRuCups: 'Э',
  },
  40: {
    code: 'Enter',
    description: 'return',
  },
  41: {
    code: 'ShiftLeft',
    description: 'shift',
  },
  42: {
    code: 'KeyZ',
    descriptionEng: 'z',
    descriptionEngCups: 'Z',
    descriptionRu: 'я',
    descriptionRuCups: 'Я',
  },
  43: {
    code: 'KeyX',
    descriptionEng: 'x',
    descriptionEngCups: 'X',
    descriptionRu: 'ч',
    descriptionRuCups: 'Ч',
  },
  44: {
    code: 'KeyC',
    descriptionEng: 'c',
    descriptionEngCups: 'C',
    descriptionRu: 'с',
    descriptionRuCups: 'С',
  },
  45: {
    code: 'KeyV',
    descriptionEng: 'v',
    descriptionEngCups: 'V',
    descriptionRu: 'м',
    descriptionRuCups: 'М',
  },
  46: {
    code: 'KeyB',
    descriptionEng: 'b',
    descriptionEngCups: 'B',
    descriptionRu: 'и',
    descriptionRuCups: 'И',
  },
  47: {
    code: 'KeyN',
    descriptionEng: 'n',
    descriptionEngCups: 'N',
    descriptionRu: 'т',
    descriptionRuCups: 'Т',
  },
  48: {
    code: 'KeyM',
    descriptionEng: 'm',
    descriptionEngCups: 'M',
    descriptionRu: 'ь',
    descriptionRuCups: 'Ь',
  },
  49: {
    code: 'Comma',
    descriptionEng: ',',
    descriptionEngCups: '<',
    descriptionRu: 'б',
    descriptionRuCups: 'Б',
  },
  50: {
    code: 'Period',
    descriptionEng: '.',
    descriptionEngCups: '>',
    descriptionRu: 'ю',
    descriptionRuCups: 'Ю',
  },
  51: {
    code: 'Slash',
    descriptionEng: '/',
    descriptionEngCups: '?',
    descriptionRu: '/',
    descriptionRuCups: '?',
  },
  52: {
    code: 'ShiftRight',
    description: 'shift',
  },
  53: {
    code: 'fn',
    description: 'fn',
  },
  54: {
    code: 'ControlLeft',
    description: 'control',
  },
  55: {
    code: 'AltLeft',
    description: 'option',
  },
  56: {
    code: 'MetaLeft',
    description: 'command',
  },
  57: {
    code: 'Space',
    description: '',
  },
  58: {
    code: 'MetaRight',
    description: 'command',
  },
  59: {
    code: 'AltRight',
    description: 'option',
  },
  60: {
    code: 'ArrowLeft',
    description: '',
  },
  61: {
    code: 'ArrowUp',
    description: '',
  },

  62: {
    code: 'ArrowRight',
    description: '',
  },
};
